name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t poring86/auth .
      - run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
        env: 
          DOCKER_USERNAME: $${ secrets.DOCKER_USERNAME }
          DOCKER_PASSWORD: $${ secrets.DOCKER_PASSWORD }
      - run: docker push poring86/auth
